# Generated by Django 2.2.14 on 2020-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('profesor', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
                ('creditos', models.CharField(max_length=200)),
            ],
        ),
    ]
