# Generated by Django 2.2.14 on 2020-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('paterno', models.CharField(max_length=200)),
                ('materno', models.CharField(max_length=200)),
                ('estatus', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('creditos', models.CharField(max_length=200)),
                ('clase', models.ManyToManyField(related_name='clase', to='clases.Clase')),
            ],
        ),
    ]
