# Generated by Django 2.2.14 on 2020-11-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='clase',
        ),
        migrations.CreateModel(
            name='ListaClases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clases.Clase')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estudiantes.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(related_name='clase', through='estudiantes.ListaClases', to='clases.Clase'),
        ),
    ]
