# Generated by Django 2.2.14 on 2020-11-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_auto_20201123_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaclases',
            old_name='clase_id',
            new_name='clase',
        ),
        migrations.RenameField(
            model_name='listaclases',
            old_name='estudiante_id',
            new_name='estudiante',
        ),
    ]
