# Generated by Django 2.2.14 on 2020-11-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_auto_20201123_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaclases',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase'),
        ),
        migrations.AlterField(
            model_name='listaclases',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiante'),
        ),
    ]
