# Generated by Django 2.2.14 on 2020-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_auto_20201123_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(related_name='estudiantes', through='estudiantes.ListaClases', to='clases.Clase'),
        ),
    ]
